# SPDX-FileCopyrightText: 2023 Digg - Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0

---
name: REUSE Compliance
on: [workflow_call] # yamllint disable-line rule:truthy

permissions:
  contents: read

jobs:
  reuse:
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'pull_request') && (github.actor != 'dependabot[bot]') }}
    steps:
      - uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 #v2.10.1
        with:
          egress-policy: audit

      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 #v4.2.0
        with:
          fetch-depth: 10

      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@3ae3c6bdf1257ab19397fab11fd3312144692083 # v4.0.0
