# SPDX-FileCopyrightText: 2024 Skatteverket - Swedish Tax Agency
#
# SPDX-License-Identifier: CC0-1.0

---
name: MegaLinter
on: [workflow_call] # yamllint disable-line rule:truthy

permissions:
  contents: read
  security-events: write

env:
  MEGALINTER_CONFIG: /development/mega-linter.yml

jobs:
  megalinter:
    name: megalint
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'pull_request') && (github.actor != 'dependabot[bot]') }}
    permissions:
      # Needed for Code scanning upload
      security-events: write

    steps:
      - name: Harden GitHub runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e #v2.10.4
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          fetch-depth: 7

      - name: Run MegaLinter
        id: ml
        uses: oxsecurity/megalinter@f90c800040e4f84800700b27b2394d3eecc1fdad # v8.4.0

      - name: Archive production artifacts
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 #v4.6.0
        with:
          name: MegaLinter reports
          path: |
            megalinter-reports

      - name: Upload Megalint Sarif Report
        uses: github/codeql-action/upload-sarif@10a3f072a02acccf25a5b381a29fbac3a805893d #v3.26.6
        with:
          sarif_file: megalinter-reports/megalinter-report.sarif
