# SPDX-FileCopyrightText: 2024 Skatteverket - Swedish Tax Agency
#
# SPDX-License-Identifier: CC0-1.0

---
name: MegaLinter
on: [workflow_call] # yamllint disable-line rule:truthy

permissions:
  contents: read
  security-events: write

env:
  MEGALINTER_CONFIG: /development/mega-linter.yml

jobs:
  megalinter:
    name: megalint
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'pull_request') && (github.actor != 'dependabot[bot]') }}
    permissions:
      # Needed for Code scanning upload
      security-events: write

    steps:
      - name: Harden GitHub runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f #v2.10.2
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          fetch-depth: 7

      - name: Run MegaLinter
        id: ml
        uses: oxsecurity/megalinter@d8c95fc6f2237031fb9e9322b0f97100168afa6e # v8.2.0

      - name: Archive production artifacts
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 #v4.4.3
        with:
          name: MegaLinter reports
          path: |
            megalinter-reports

      - name: Upload Megalint Sarif Report
        uses: github/codeql-action/upload-sarif@46e0c78da9edf293aeab3d4d62cf1a7b7534c6a0 #v3.26.6
        with:
          sarif_file: megalinter-reports/megalinter-report.sarif
